version: "3.10"

services:
  app:
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - HF_TOKEN=$HF_TOKEN
        - OPENAI_API_KEY=$OPENAI_API_KEY
    volumes:
      - .:/app
    devices:
      - /dev/neuron0:/dev/neuron0
    ports:
      - target: 8501       ## 컨테이너 내부 포트
        published: 8501    ## 호스트OS에서 공개할 포트
        protocol: tcp      ## 포트 프로토콜
    environment:
      - FLASK_ENV=development
      - MAX_JOBS=4
    command:
      - poetry run serve run summary_serv:build_app
