version: "3.10"

services:
  app:
    env_file:
      - .env
    volumes:
      - .:/app
      - /home/conan/.cache:/root/.cache
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - HF_TOKEN=$HF_TOKEN
        - OPENAI_API_KEY=$OPENAI_API_KEY
    # devices:
    #   - /dev/neuron0:/dev/neuron0
    ports:
      - target: 8501       ## 컨테이너 내부 포트
        published: 8510    ## 호스트OS에서 공개할 포트
        protocol: tcp      ## 포트 프로토콜
    environment:
      - FLASK_ENV=development
      - MAX_JOBS=4
      - HF_TOKEN=$HF_TOKEN
      - LD_LIBRARY_PATH=$LD_LIBRARY_PATH
      - SYSTEM_NAME=$SYSTEM_NAME
    runtime: nvidia
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 16gb
        reservations:
          cpus: '2'
          memory: 16gb
          devices:
          - driver: nvidia
            device_ids: ['0']
            capabilities: [gpu]
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    command: 
      - serve
      - run
      - summary_serv:build_app
      - port=8501
