summarize_description = (
    "dencomm sLLM 상담 내역 텍스트 요약 API."
    "\n\n"
    "HTTP Method: POST\n\n"
    "**SummaryRequest**\n"
    "   - *text [str]: 요약할 텍스트.\n"
    "   - prompt_type [str(Optional)]: 요약에 사용할 프롬프트 유형. 기본값은 'dental'.\n"
    "   - prompt [str(Optional)]:  요약에 사용할 프롬프트. prompt type 지정된 경우 무시됨.\n"
    "   - language [str(Optional)]: 요약 결과 언어. 지정하지 않으면 영어(en)로 요약.\n"
    "\n"
    "       prompt type\n\n"
    "           - detanl: (Default) 치과\n"
    "           - beauty: 피부과/성형외과\n"
    "           - mental: 정신의학과\n"
    "\n"
    "       language code\n\n"
    "           - ko: 한국어\n"
    "           - en: 영어\n"
    "\n"
    "**SummaryResponse**\n"
    "   - text: 요약된 텍스트."
)

summarize_sllm_stream_description = (
    "dencomm sLLM 상담 내역 텍스트 요약 API."
    "\n\n"
    "HTTP Method: POST\n\n"
    "**SummaryRequest**\n"
    "   - *text [str]: 요약할 텍스트.\n"
    "   - prompt_type [str(Optional)]: 요약에 사용할 프롬프트 유형. 기본값은 'dental'.\n"
    "   - prompt [str(Optional)]:  요약에 사용할 프롬프트. prompt type 지정된 경우 무시됨.\n"
    "   - language [str(Optional)]: 요약 결과 언어. 지정하지 않으면 영어(en)로 요약.\n"
    "\n"
    "       prompt type\n\n"
    "           - detanl: (Default) 치과\n"
    "           - beauty: 피부과/성형외과\n"
    "           - mental: 정신의학과\n"
    "\n"
    "       language code\n\n"
    "           - ko: 한국어\n"
    "           - en: 영어\n"
    "\n"
    "**Streaming Response**\n"
    "   - text: 요약된 텍스트. 모델에서 생성되는 단어마다 Streaming Response로 전달됨."
)

summarize_sllm_description = (
    "상담 내역 텍스트 요약 API."
    "\n\n"
    "HTTP Method: POST\n\n"
    "**SummaryRequest**\n"
    "   - *text: 요약할 텍스트.\n"
    "   - prompt_type [str(Optional)]: 요약에 사용할 프롬프트 유형. 기본값은 'dental'.\n"
    "   - prompt [str(Optional)]:  요약에 사용할 프롬프트. prompt type 지정된 경우 무시됨.\n"
    "   - language [str(Optional)]: 요약 결과 언어. 지정하지 않으면 영어(en)로 요약.\n"
    "\n"
    "       prompt type\n\n"
    "           - detanl: 치과  (default)\n"
    "           - beauty: 피부과/성형외과\n"
    "           - mental: 정신의학과\n"
    "\n"
    "       language code\n\n"
    "           - ko: 한국어\n"
    "           - en: 영어\n"
    "\n"
    "**SummaryResponse**\n"
    "   - text: 요약된 텍스트."
)

healthcheck_description = (
    "서비스 상태를 확인하는 API.\n\n"
    "서버가 정상적으로 작동 여부 확인.\n\n"
    "**Response**\n"
    "   - message: 'ok' (서버가 정상적으로 작동 중일 때)"
)

