translate_description = (
    "dencomm transera 실시간 번역 API."
    "\n\n"
    "HTTP Method: POST\n\n"
    "**TranslateRequest**\n"
    "   - *text [str]: 번역할 텍스트.\n"
    "   - *source_language [str]: 입력 텍스트의 언어. language code 값 요청.\n"
    "   - *target_language [list[str]]: 번역할 언어 리스트. language code 값 요청.\n"
    "   - history [list[str] (Optional)]: 발화자의 이전 발호 stt 결과. 번역 맥락 유지를 위해 사용됨.\n"
    "\n"
    "       language code\n\n"
    "           - Korean: ko\n"
    "           - English: en\n"
    "           - Chinese: zh\n"
    "           - French: fr\n"
    "           - Spanish: es\n"
    "           - Italian: it\n"
    "           - German: de\n"
    "\n"
    "**TranslateResponse**\n"
    "   - text [str]: 요청 text의 번역된 결과.\n"
    "   - source_language [str]: 입력 텍스트의 언어.\n"
    "   - target_language [list[str]]: 번역된 언어.\n"
    "   - translations [Dict[str, str]]: 언어별 번역 결과 Object."
)

translate_summary_description = (
    "dencomm transera 강연 요약 API."
    "\n\n"
    "HTTP Method: POST\n\n"
    "**TranslateRequest**\n"
    "   - *text [str]: 요약약할 텍스트.\n"
    "   - *source_language [str]: 입력 텍스트의 언어. language code 값 요청.\n"
    "   - *target_language [list[str]]: 번역할 언어 리스트. language code 값 요청.\n"
    "   - history [list[str] (Optional)]: 강연 결과 요약시에는 따로 사용하지 않음.\n"
    "\n"
    "       language code\n\n"
    "           - Korean: ko\n"
    "           - English: en\n"
    "           - Chinese: zh\n"
    "           - French: fr\n"
    "           - Spanish: es\n"
    "           - Italian: it\n"
    "           - German: de\n"
    "\n"
    "**SummaryResponse**\n"
    "   - text [str]: 요청 text의 요약 결과."
)

translate_sllm_description = (
    "dencomm transera sllm 실시간 번역 API."
    "\n\n"
    "HTTP Method: POST\n\n"
    "**TranslateRequest**\n"
    "   - *text [str]: 번역할 텍스트.\n"
    "   - *source_language [str]: 입력 텍스트의 언어. language code 값 요청.\n"
    "   - *target_language [list[str]]: 번역할 언어 리스트. language code 값 요청.\n"
    "   - history [list[str] (Optional)]: 발화자의 이전 발호 stt 결과. 번역 맥락 유지를 위해 사용됨.\n"
    "\n"
    "       language code\n\n"
    "           - Korean: ko\n"
    "           - English: en\n"
    "           - Chinese: zh\n"
    "           - French: fr\n"
    "           - Spanish: es\n"
    "           - Italian: it\n"
    "           - German: de\n"
    "\n"
    "**TranslateResponse**\n"
    "   - text [str]: 요청 text의 번역된 결과.\n"
    "   - source_language [str]: 입력 텍스트의 언어.\n"
    "   - target_language [list[str]]: 번역된 언어.\n"
    "   - translations [Dict[str, str]]: 언어별 번역 결과 Object."
)

translate_summary_sllm_description = (
    "dencomm transera sllm 실시간 번역 API."
    "\n\n"
    "HTTP Method: POST\n\n"
    "**TranslateRequest**\n"
    "   - *text [str]: 요약약할 텍스트.\n"
    "   - *source_language [str]: 입력 텍스트의 언어. language code 값 요청.\n"
    "   - *target_language [list[str]]: 번역할 언어 리스트. language code 값 요청.\n"
    "   - history [list[str] (Optional)]: 강연 결과 요약시에는 따로 사용하지 않음.\n"
    "\n"
    "       language code\n\n"
    "           - Korean: ko\n"
    "           - English: en\n"
    "           - Chinese: zh\n"
    "           - French: fr\n"
    "           - Spanish: es\n"
    "           - Italian: it\n"
    "           - German: de\n"
    "\n"
    "**SummaryResponse**\n"
    "   - text [str]: 요청 text의 요약 결과."
)

text_split_description = (
    "dencomm transera 문장 분리 API."
    "\n\n"
    "**TextSplitRequest**\n"
    "   - *text [str]: 분리할 텍스트.\n"
    "\n"
    "**TextSplitResponse**\n"
    "   - splited_sentences [list[str]]: 분리된 문장 리스트.\n"
    "   - completed_sentence [str]:  완성된 문장이 있는 경우 해당 문장. 문장이 완성되지 않은 경우 공백으로 전달됨.\n"
    "   - uncompleted_sentence [str]:  아직 완성되지 않은 문장.\n"
    "   - translation_flag [bool]: 번역 가능 여부 flag (TRUE: 번역 진행 / FALSE: 번역 진행X)."
)