version: "3.10"

services:
  app:
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - HF_TOKEN=$HF_TOKEN
    volumes:
      - .:/app
    ports:
      - "8502:8502"
    environment:
      - FLASK_ENV=development
    command: gunicorn deploy:app --workers 1 --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:8502
  